# kafo main configuration file example
# you can rename it to kafo.yaml so it overwrite default kafo settings
# note current configuration is written tokafo.yaml every time kafo is run

## Useful for development, e.g. when you want to move log files to local directory
# :log_dir: '/var/log/kafo'
# :log_level: :info

## Kafo tuning, customization of core functionality
# :no_prefix: false
# :mapping: {}
# :order:

## Advanced configuration - if not set it's ignored
# :log_owner: root
# :log_group: root

:log_level: :debug
:log_dir: /var/log/katello-installer
:log_name: capsule-certs-generate.log
:no_prefix: true
:answer_file: ./config/answers.capsule-certs-generate.yaml
:installer_dir: .
:modules_dir: "./modules"
:hooks_dir: "./hooks"
:default_values_dir: ./config
:dont_save_answers: true
:mapping:
  :capsule_certs:
    :manifest_name: capsule
    :dir_name: certs
:order:
  - certs
  - capsule_certs
