---
:name: Katello
:description: Install Foreman with Katello
:log_dir: /var/log/foreman-installer
:log_name: katello.log
:log_level: DEBUG
:no_prefix: false
:answer_file: ./config/katello-answers.yaml
:installer_dir: .
:default_values_dir: ./config
:module_dirs:
- ./_build/modules
- ../katello-installer/modules
:parser_cache_path:
- /usr/share/foreman-installer/parser_cache/foreman.yaml
- /usr/share/katello-installer-base/parser_cache/katello.yaml
:hiera_config: /usr/share/foreman-installer/config/foreman-hiera.conf
:hook_dirs:
- ../katello-installer/hooks
:colors: true
:order:
- certs
- foreman
- katello
- foreman_proxy
- foreman_proxy::plugin::pulp
- capsule
# Unused, but remains present for older config migrations
:mapping: {}
